# Generated by Django 5.2.1 on 2025-07-29 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_remove_lecture_order'),
        ('quiz', '0003_courseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursesection'),
        ),
    ]
