# Generated by Django 5.2.1 on 2025-08-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_remove_lecture_order'),
        ('quiz', '0004_courseitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseitems', to='lms.course'),
        ),
    ]
