# Generated by Django 5.2.1 on 2025-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_courseitem_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseitem',
            options={'ordering': ['order'], 'verbose_name': 'Course item order', 'verbose_name_plural': 'Course Item orders'},
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], default='MCQ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
