# Generated by Django 5.2.1 on 2025-08-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_review_show'),
        ('quiz', '0006_alter_courseitem_options_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('Radio', 'Radio')], default='MCQ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_for_course', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.coursesection'),
        ),
    ]
