# Generated by Django 5.2.1 on 2025-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='page_type',
            field=models.CharField(blank=True, choices=[('basic_page', 'Главный')], max_length=50, null=True),
        ),
    ]
