# Generated by Django 5.2.1 on 2025-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_article_options_blogs_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='helper_text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='helper_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='helper_text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='helper_text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='helper_text5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
