# Generated by Django 5.2.1 on 2025-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_blogs_helper_text1_en_blogs_helper_text1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogs', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_type',
            field=models.CharField(blank=True, choices=[('online_platform_education', 'Online Platform Education'), ('top_categories', 'Top Categories'), ('global_education', 'Global Education'), ('top_course', 'Top Course'), ('becoming_a_tutor', 'Becoming a Tutor')], max_length=50, null=True),
        ),
    ]
