# Generated by Django 5.2.1 on 2025-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_blogs_course_alter_blogs_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='lms.course'),
        ),
    ]
