# Generated by Django 5.2.1 on 2025-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_blogs_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video',
        ),
        migrations.AddField(
            model_name='course',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
