# Generated by Django 5.2.1 on 2025-07-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='course',
        ),
    ]
