# Generated by Django 5.2.1 on 2025-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_blogs_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
