# Generated by Django 5.2.1 on 2025-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_blogs_vimeo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
