# Generated by Django 5.2.1 on 2025-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='helper_text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
