# Generated by Django 5.2.1 on 2025-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_tutor_helper_text1_tutor_helper_text2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='helper_text1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='helper_text3_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TutorBulletPoint',
        ),
    ]
