# Generated by Django 5.2.1 on 2025-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_tutor_helper_text1_en_tutor_helper_text1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
    ]
