# Generated by Django 5.2.1 on 2025-07-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
