# Generated by Django 5.2.1 on 2025-07-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_tutor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='organiser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='organiser_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='organiser_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='start_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
