# Generated by Django 5.2.1 on 2025-07-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_article_cost_article_end_hour_article_helper_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='helper_text3_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
