# Generated by Django 5.2.1 on 2025-07-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_article_description_en_article_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
