# Generated by Django 5.2.1 on 2025-07-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
