# Generated by Django 5.2.1 on 2025-07-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_article_category_en_article_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='tutor',
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_qualifications', to='lms.qualification'),
        ),
    ]
