# Generated by Django 5.2.1 on 2025-07-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_remove_qualification_tutor_tutor_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_qualifications', to='lms.qualification'),
        ),
    ]
