# Generated by Django 5.2.1 on 2025-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_alter_course_course_type_alter_course_course_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
