# Generated by Django 5.2.1 on 2025-07-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_lecture_title_en_lecture_title_ru_lecture_title_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_qualifications', to='lms.tutor'),
        ),
    ]
