# Generated by Django 5.2.1 on 2025-07-28 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_usercourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lms.coursesection'),
        ),
    ]
