# Generated by Django 5.2.1 on 2025-07-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_remove_question_quiz_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='order',
        ),
    ]
