# Generated by Django 5.2.1 on 2025-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_remove_lecture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
